optimization:
  token_budgets:
    claude-3-opus: 200000
    claude-3-sonnet: 100000
    gpt-4: 8000
    gpt-4-32k: 32000
    local-llm: 4000

  scoring_weights:
    recency: 10
    task_relevance: 20
    project_match: 15
    frequency: 5
    entity_overlap: 8
    error_solutions: 12
    user_importance: 10

  compression:
    enable_code_compression: true
    enable_conversation_summary: true
    max_memory_age_days: 90
    archive_after_days: 30
